Name:  Sana Raza

Labpartner(s)

In [1]:
#import statements go here
import pandas as pd
import numpy as np

# Class 9.1

I'm out sick today, but you all are advanced so I know you will be productive without me.

# Warmup 9.1

**W.1** Create the following numpy array. Print out the values to check!

[[0. 0. 0. 0. 0. 0. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 5. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 0. 0. 0. 0. 0. 0.]]

In [2]:
arr = np.zeros((7, 7))
arr[1:6, 1:6] = 1 # sets the inner 5×5 block rows and columns from 1- 5 to 1
arr[3, 3] = 5 # puts 5 in the center
print(arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

**W.2** Pandas filtering and sorting practice with Chipotle data

Import the dataset from this address https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv
Assign it to a variable called chipo.
1. How many products cost more than $10.00?
2. What is the price of each item?
    1. Print a data frame with only two columns item_name and item_price
    2. Sort by the name of the item
1. What was the quantity of the most expensive item ordered?
1. How many times did someone order more than one Canned Soda?

In [3]:
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep="\t")
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [4]:
chipo.loc[(chipo["choice_description"] == '[Diet Coke]') & (chipo["item_name"] == "Canned Soda")]

      order_id  quantity    item_name choice_description item_price
162         73         2  Canned Soda        [Diet Coke]     $2.18
200         89         1  Canned Soda        [Diet Coke]     $1.09
317        138         1  Canned Soda        [Diet Coke]     $1.09
350        150         2  Canned Soda        [Diet Coke]     $2.18
370        160         1  Canned Soda        [Diet Coke]     $1.09
779        321         1  Canned Soda        [Diet Coke]     $1.09
1216       496         1  Canned Soda        [Diet Coke]     $1.09
1662       672         1  Canned Soda        [Diet Coke]     $1.09
1953       790         1  Canned Soda        [Diet Coke]     $1.09
2135       859         2  Canned Soda        [Diet Coke]     $2.18
2544      1009         1  Canned Soda        [Diet Coke]     $1.09
2850      1132         1  Canned Soda        [Diet Coke]     $1.09
3592      1440         2  Canned Soda        [Diet Coke]     $2.18
3793      1518         1  Canned Soda        [Diet Coke]     $1.09
4008      1604         1  Canned Soda        [Diet Coke]     $1.09

In [5]:
chipo["item_price"] = chipo["item_price"].str.replace("$", "", regex=False).astype(float)
chipo["product_price"] = chipo["item_price"] / chipo["quantity"]
chipo

,order_id,quantity,item_name,choice_description,item_price,product_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

In [6]:
#checking everything is correct
chipo.loc[(chipo["choice_description"] == '[Diet Coke]') & (chipo["item_name"] == "Canned Soda")]

,order_id,quantity,item_name,choice_description,item_price,product_price
162,73,2,Canned Soda,[Diet Coke],2.18,1.09
200,89,1,Canned Soda,[Diet Coke],1.09,1.09
317,138,1,Canned Soda,[Diet Coke],1.09,1.09
350,150,2,Canned Soda,[Diet Coke],2.18,1.09
370,160,1,Canned Soda,[Diet Coke],1.09,1.09
779,321,1,Canned Soda,[Diet Coke],1.09,1.09
1216,496,1,Canned Soda,[Diet Coke],1.09,1.09
1662,672,1,Canned Soda,[Diet Coke],1.09,1.09
1953,790,1,Canned Soda,[Diet Coke],1.09,1.09
2135,859,2,Canned Soda,[Diet Coke],2.18,1.09
2544,1009,1,Canned Soda,[Diet Coke],1.09,1.09
2850,1132,1,Canned Soda,[Diet Coke],1.09,1.09
3592,1440,2,Canned Soda,[Diet Coke],2.18,1.09
3793,1518,1,Canned Soda,[Diet Coke],1.09,1.09
4008,1604,1,Canned Soda,[Diet Coke],1.09,1.09

In [7]:
# removing duplicated products
filtered_chipo=chipo.drop_duplicates(['item_name','choice_description'])

In [8]:
# filtering products that costs more than $10
filtered_chipo = filtered_chipo.loc[ filtered_chipo["product_price"]>10.0 , ["item_name","choice_description","product_price"] ].reset_index(drop=True)

In [9]:
filtered_chipo[["item_name","choice_description","product_price"]]

,item_name,choice_description,product_price
0,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
3,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
4,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
...,...,...,...
702,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75
703,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",11.75
704,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
705,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
706,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25

In [10]:
# data frame with only item_name and item_price, sorted by item name
chipo[["item_name", "item_price"]].sort_values("item_name")

              item_name  item_price
298   6 Pack Soft Drink        6.49
341   6 Pack Soft Drink        6.49
357   6 Pack Soft Drink        6.49
388   6 Pack Soft Drink        6.49
417   6 Pack Soft Drink        6.49
...                 ...         ...
1395  Veggie Soft Tacos        8.49
1699  Veggie Soft Tacos       11.25
2384  Veggie Soft Tacos        8.75
2851  Veggie Soft Tacos        8.49
3889  Veggie Soft Tacos       16.98

[4622 rows x 2 columns]

In [11]:
chipo.loc[chipo["item_price"].idxmax()]["quantity"]

np.int64(15)

In [12]:
chipo[chipo["item_name"]=="Veggie Salad Bowl"]["quantity"].sum()

np.int64(18)

In [13]:
chipo[ ( chipo["item_name"]=="Canned Soda" ) & ( chipo["quantity"]>1 )].shape[0]

20

# Lecture 9.1

### Agenda:

- Questions
- Exchange proposal outlines with your labmate.
- LaTeX tutorial

### Questions

If you have questions, please pose them to the class. You can also send me a slack message.

# Lab 9.1

**E.0** Complete the previous labs if you are behind.

**E.1** Share your proposal outline with your lab partner. Give each other fedback. Consult the rubric and checklist. Do you have all the graded components? What needs work?

Discussed with the lab partner

**E.2** Complete the tutorial "Learn LaTeX in 30 min" here: https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes

Make a sample document in LaTeX showing what you learned and submit the PDF along with your lab in Moodle.

**E.3** Using a CV template in Overleaf, make an academic CV for yourself. Put the PDF of your CV on github and link in Moodle

**E.4** Ask your supervisor for a proposal sample. This could be a proposal another student in your lab has written, or a proposal your PI has written. Use this to inform your proposal writing style. If it's okay with your PI to share, upload it onto github to share with others in the class and submit a link. If it's not for sharing, upload a copy to Moodle. You can consult previous class' github for more samples.

**Notes** Make notes for yourself on progamming tecniques and commands you learned in the this week, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.


```latex
\documentclass[12pt]{article}   
\usepackage{graphicx}           # packages add features (here: images)
\title{My Title}
\author{Sana Raza}
\date{\today}                   # today's date, updated on each compile
\begin{document}
\maketitle                      # prints the title, author and date
...
\end{document}
```

- Structure: `\section{...}`, `\subsection{...}`, `\section*{...}` (unnumbered), `\tableofcontents`.
- Text formatting: `\textbf{bold}`, `\textit{italic}`, `\underline{underlined}`, `\emph{emphasis}`.
- Lists: `itemize` for bullet points, `enumerate` for numbered lists, each entry starts with `\item`.
- Math: inline with `$E=mc^2$`; numbered display equations with `\begin{equation} ... \end{equation}`.
- Figures:
```latex
\begin{figure}[htbp]
    \centering
    \includegraphics[width=0.6\textwidth]{scatter}  % file name without extension
    \caption{My caption.}
    \label{fig:scatter}
\end{figure}
```