Name: <span style="color:olivedrab"> Maya Maes-Johnson </span>

Labpartner(s): <span style="color:olivedrab"> Haoxin Ni </span>

In [1]:
#import statements go here
import numpy as np
import pandas as pd

# Class 9.1

I'm out sick today, but you all are advanced so I know you will be productive without me.

# Warmup 9.1

**W.1** Create the following numpy array. Print out the values to check!

[[0. 0. 0. 0. 0. 0. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 5. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 0. 0. 0. 0. 0. 0.]]

In [2]:
# Array of floats size (7, 7) padded by zeros & center as 5

my_array = np.zeros([7,7])
my_array[1:6,1:6] = 1
my_array[3:4,3:4] = 5

print(my_array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

**W.2** Pandas filtering and sorting practice with Chipotle data

Import the dataset from this address https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv
Assign it to a variable called chipo.
1. How many products cost more than $10.00?
2. What is the price of each item?
    1. Print a data frame with only two columns item_name and item_price
    2. Sort by the name of the item
1. What was the quantity of the most expensive item ordered?
1. How many times did someone order more than one Canned Soda?

In [3]:
chipotle = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')

chipotle.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [4]:
# Convert item_price to float:

price_as_float = []
for price in chipotle["item_price"]:
    price_as_float.append(float(price[1:]))

chipotle["price_float"] = price_as_float

chipotle.head()

,order_id,quantity,item_name,choice_description,item_price,price_float
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
1,1,1,Izze,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98

In [14]:
# How many products cost more than $10.00?
chipotle[chipotle["price_float"] > 10.].count()

order_id              1130
quantity              1130
item_name             1130
choice_description    1123
item_price            1130
price_float           1130
dtype: int64

<span style="color:olivedrab"> There are 1130 products with a price greater than $1000. </span>

In [16]:
# What is the price of each item?
item_name_price = chipotle[['item_name', 'price_float']].copy()
item_name_price.sort_values('item_name')

              item_name  price_float
298   6 Pack Soft Drink         6.49
341   6 Pack Soft Drink         6.49
357   6 Pack Soft Drink         6.49
388   6 Pack Soft Drink         6.49
417   6 Pack Soft Drink         6.49
...                 ...          ...
1395  Veggie Soft Tacos         8.49
1699  Veggie Soft Tacos        11.25
2384  Veggie Soft Tacos         8.75
2851  Veggie Soft Tacos         8.49
3889  Veggie Soft Tacos        16.98

[4622 rows x 2 columns]

In [19]:
# What was the qty of the most expensive iten ordered?
chipotle[chipotle['price_float'] == chipotle['price_float'].max()]

,order_id,quantity,item_name,choice_description,item_price,price_float
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25,44.25

<span style="color:olivedrab"> The quantity of the most expensive item sold was 15. </span>

In [26]:
#How many times did someone order more than one canned soda?

chipotle[(chipotle['item_name'] == 'Canned Soda') & (chipotle['quantity'] > 1)].count()

order_id              20
quantity              20
item_name             20
choice_description    20
item_price            20
price_float           20
dtype: int64

<span style="color:olivedrab"> There 20 instances of someone ordering more than one canned soda. </span>

# Lecture 9.1

### Agenda:

- Questions
- Exchange proposal outlines with your labmate.
- LaTeX tutorial

### Questions

If you have questions, please pose them to the class. You can also send me a slack message.

# Lab 9.1

**E.0** Complete the previous labs if you are behind.

**E.1** Share your proposal outline with your lab partner. Give each other fedback. Consult the rubric and checklist. Do you have all the graded components? What needs work?

**E.2** Complete the tutorial "Learn LaTeX in 30 min" here: https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes

Make a sample document in LaTeX showing what you learned and submit the PDF along with your lab in Moodle.

**E.3** Using a CV template in Overleaf, make an academic CV for yourself. Put the PDF of your CV on github and link in Moodle

**E.4** Ask your supervisor for a proposal sample. This could be a proposal another student in your lab has written, or a proposal your PI has written. Use this to inform your proposal writing style. If it's okay with your PI to share, upload it onto github to share with others in the class and submit a link. If it's not for sharing, upload a copy to Moodle. You can consult previous class' github for more samples.

**Notes** Make notes for yourself on progamming tecniques and commands you learned in the this week, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

<span style="color:olivedrab"> Below is some LaTeX I did not include in my document because it would have required starting a new document class:</span>

In [ ]:
\documentclass{book}
\begin{document}

\chapter{First Chapter}

\section{Introduction}

This is the first section.

Lorem  ipsum  dolor  sit  amet,  consectetuer  adipiscing  
elit. Etiam  lobortisfacilisis sem.  Nullam nec mi et 
neque pharetra sollicitudin.  Praesent imperdietmi nec ante. 
Donec ullamcorper, felis non sodales...

\section{Second Section}

Lorem ipsum dolor sit amet, consectetuer adipiscing elit.  
Etiam lobortis facilisissem.  Nullam nec mi et neque pharetra 
sollicitudin.  Praesent imperdiet mi necante...

\subsection{First Subsection}
Praesent imperdietmi nec ante. Donec ullamcorper, felis non sodales...

\section*{Unnumbered Section}
Lorem ipsum dolor sit amet, consectetuer adipiscing elit.  
Etiam lobortis facilisissem...
\end{document}

In [ ]:
# How to use packages:
\usepackage[options]{somepackage}